"""add: fixed foreign key to be able to be nullable

Revision ID: 382f81bf9376
Revises: 8e5856845f39
Create Date: 2024-06-10 09:51:49.453540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f81bf9376'
down_revision = '8e5856845f39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
